# File for whitelisting frameworks downloaded using carthage_cache: https://github.com/Wolox/carthage_cache
"WolmoReactiveCore": "wolmo-reactive-core-ios"
"WolmoCore": "wolmo-core-ios"
"Rollbar": "rollbar-ios"
