version: "2"
#prepare example
#prepare:
#  fetch:
#    - url: "https://raw.githubusercontent.com/example/example/master/rubocop.yml"
#      path: "alternate-rubocop-path.yml"
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 25
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
#plugins example
#plugins:
#  rubocop:
#    enabled: true
#    channel: "rubocop-0-49"
#    checks:
#      Rubocop/Style/TrailingCommaInLiteral:
#        enabled: false
#    config:
#      file: "alternate-rubocop-path.yml"
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "*tests/"
