config:
  ci: 'BITRISE'
  url: http://codestats.wolox.com.ar/
  token: <%= ENV['CODE_STATS_TOKEN'] %>
metrics:
  slather:
    enabled: true
    minimum: 70
    upload_report: false
  swiftlint:
    enabled: true
    minimum: 90
    upload_report: false
  tailor:
    enabled: false
    minimum: 90
    upload_report: false
