xcodeproj: ./BaseProject.xcodeproj
scheme: BaseProject
ignore:
  - BaseProject/AppDelegate.swift
  - BaseProject/Environment.swift
  - BaseProject/Services/RollbarService.swift
  - BaseProjectTests/*
  - BaseProjectUITests/*
