disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - variable_name
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - BaseProjectTests
  - BaseProjectUITests
line_length: 200
function_body_length: 20
