language: objective-c
osx_image: xcode7.3
before_install:
- gem install bundler
script:
- REPO_SLUG="$TRAVIS_REPO_SLUG" PULL_REQUEST="$TRAVIS_PULL_REQUEST" DISABLE_SWIFTLINT_RUN_SCRIPT=true FORCE_CARTHAGE_VERSION=true FORCE_SWIFTLINT_VERSION=true script/cibuild
after_success: bundle exec slather
branches:
  only:
  - master
env:
  global:
notifications:
  email:
    - baseproject-ios-dev@wolox.com.ar
