# The env variables are contained in an `.env.default` file.
fastlane_version "2.36.0"
default_platform :ios

# Default path formatters
project_plist_path = "%s/Info.plist"
project_xcconfig_path = "%s/ConfigurationFiles/%s.xcconfig"
dsym_zip_path = "%s.app.dSYM.zip"

# Default build configuration by action
build_configurations = {
  test: "Development",
  qa: "Alpha",
  testflight: "Beta",
  release: "Production"
}

# Default match types by build configuration
match_types = {
  test: "development",
  qa: "adhoc",
  testflight: "appstore",
  release: "appstore"
}

# Default App ID names by build configuration
app_names = {
  test: "%s Dev",
  qa: "%s Alpha",
  testflight: "%s",
  release: "%s"
}

platform :ios do

  # Run this before doing anything else
  before_all do

    # Uncomment this if you don't have the carthage frameworks installed.
    # carthage(
    #   platform: "iOS",
    #   use_binaries: false,
    #   use_ssh: true
    # )

  end

  # After all the steps have completed succesfully, run this.
  after_all do |lane|

    desc "Remove all build artifacts created by fastlane to upload."
    clean_build_artifacts

  end

  # If there was an error, run this.
  error do |lane, exception|

    desc "Remove all build artifacts created by fastlane to upload."
    clean_build_artifacts

  end

  desc "Releases a new version to `TestFlight`. This lane uses the configuration mapped to `:testflight`."
  desc ""
  desc "It has basically 3 main responsabilities: build number managing, app building, and deploy."
  desc ""
  desc "- Reads the build number from `'CURRENT_PROJECT_VERSION'` xcode build configuration for the configuration in use."
  desc "- Increments and saves this new value in the xcode build configuration."
  desc "- Sets this incremented value in the `Info.plist` under the key `CFBundleVersion`, to use this bundle version for the app."
  desc "- Builds the app using `gym` and `match` to get the signing identity. The provisioning profile in use is the one \
selected in xcode for the configuration mapped by `:testflight`."
  desc "- Uploads the generated `.dsym` file to `Rollbar`."
  desc "- Discards the value updated in `Info.plist`. Given this file is used for every configuration, these values are stored \
in xcode build configuration and just reflected in `Info.plist` when building."
  desc "- Uploads the application to `TestFlight` using `pilot`."
  desc ""
  desc "NOTE: It's important to note that in case the the version number needs to be updated, it has to be manually done, \
editing the `'CFBundleShortVersionString'` key from `Info.plist`."
  lane :release_testflight do

    desc "Read the build number from project build settings."
    current_build_number = read_project_property(
      build_configuration: build_configurations[:testflight],
      build_setting: 'CURRENT_PROJECT_VERSION'
    )

    next_build_number = String(current_build_number.to_i + 1)

    desc "Update the build number in project build settings."
    update_project_property(
      build_configuration: build_configurations[:testflight],
      build_setting: 'CURRENT_PROJECT_VERSION',
      build_setting_value: next_build_number
    )

    desc "Back up the build number in `Info.plist`."
    info_plist_backup_build_number = get_info_plist_value(
      path: project_plist_path % ENV['PROJECT_NAME'],
      key: 'CFBundleVersion'
    )

    desc "Update the build number in `Info.plist`."
    set_info_plist_value(
      path: project_plist_path % ENV['PROJECT_NAME'],
      key: 'CFBundleVersion',
      value: next_build_number
    )

    desc "Bundle identifier from xCode project"
    bundle_identifier = read_project_property(
      build_configuration: build_configurations[:testflight],
      build_setting: 'PRODUCT_BUNDLE_IDENTIFIER'
    )

    desc "Build"
    build_app(
      app_identifier: bundle_identifier,
      configuration: build_configurations[:testflight],
      match_type: match_types[:testflight],
      project_name: ENV["PROJECT_NAME"]
    )

    desc "Get rollbar server access token from configuration file."
    rollbar_server_access_token = read_xcconfig_property(
      xcconfig_path: project_xcconfig_path % [ENV['PROJECT_NAME'], build_configurations[:testflight]],
      xcconfig_key: 'ROLLBAR_SERVER_ACCESS_TOKEN'
    )

    desc "Upload dsym to rollbar."
    upload_dsym(
      access_token: rollbar_server_access_token,
      version: next_build_number,
      bundle_identifier: bundle_identifier,
      dsym_zip_path: dsym_zip_path % ENV['PROJECT_NAME']
    )

    desc "Put back the backed up build number in `Info.plist`."
    set_info_plist_value(
      path: project_plist_path % ENV['PROJECT_NAME'],
      key: 'CFBundleVersion',
      value: info_plist_backup_build_number
    )

    desc "Upload the built app to TestFlight."
    publish_testflight

  end

  desc "Executes the tests for the project using `scan`. This lane uses the configuration mapped to `:test`."
  lane :test do

    desc "Run scan with default project and scheme"
    scan(
      configuration: build_configurations[:test],
      clean: false
    )

  end

  desc "Creates the `App ID` and `Provisioning Profile` for the configurations mapped to `:test` and `:qa`."
  lane :create_development_app do

    desc "Remember after this point to choose this profile in xCode Signing (Development)"
    create_app(
      app_name: app_names[:test] % ENV['PROJECT_NAME'],
      build_configuration: build_configurations[:test],
      team_name: ENV['TEAM_NAME'],
      skip_itc: true,
      match_type: match_types[:test],
    )

    desc "Remember after this point to choose this profile in xCode Signing (Alpha)"
    create_app(
      app_name: app_names[:qa] % ENV['PROJECT_NAME'],
      build_configuration: build_configurations[:qa],
      team_name: ENV['TEAM_NAME'],
      skip_itc: true,
      match_type: match_types[:qa],
    )

  end

  desc "Creates the `App ID` and `Provisioning Profile` for the configuration mapped to `:testflight`."
  lane :create_testflight_app do
    
    desc "Remember after this point to choose this profile in xCode Signing (Beta)"
    create_app(
      app_name: app_names[:testflight] % ENV['PROJECT_NAME'],
      build_configuration: build_configurations[:testflight],
      team_name: ENV['TEAM_NAME'],
      skip_itc: true,
      match_type: match_types[:testflight],
    )

  end

  desc "Adds a new device and regenerates the `Provisioning Profile`s to include it."
  lane :add_device do

    desc "Ask the user for device name and device UUID"
    device_name = prompt(text: 'Enter the device name: ')
    device_udid = prompt(text: 'Enter the device UDID: ')
    device_hash = {}
    device_hash[device_name] = device_udid

    desc "Register new device."
    register_devices(
      devices: device_hash
    )

    desc "Refresh provisioning profiles adding the new device."
    match(
      force_for_new_devices: true
    )

  end

  desc "Builds the app creating the `.ipa` and `.dsym` files"
  private_lane :build_app do |options|

    desc "Download provisioning profiles"
    match(
      app_identifier: options[:app_identifier],
      type: options[:match_type],
      readonly: true
    )

    desc "Build the app using default project and scheme"
    gym(
      configuration: options[:configuration],
      include_symbols: true,
      # bitcode is disabled for the dsym file to keep valid after app is uploaded to app store
      # http://krausefx.com/blog/download-dsym-symbolication-files-from-itunes-connect-for-bitcode-ios-apps
      include_bitcode: false
    )

  end

  desc "Create App ID and Provisioning Profile in Member Center"
  desc "Keep these new certificates and profiles in sync with Match repository"
  private_lane :create_app do |options|

    desc "Bundle identifier from xCode project"
    bundle_identifier = read_project_property(
      build_configuration: options[:build_configuration],
      build_setting: 'PRODUCT_BUNDLE_IDENTIFIER'
    )

    desc "Create App ID in developer center"
    produce(
      app_name: options[:app_name],
      app_identifier: bundle_identifier,
      team_name: options[:team_name],
      skip_itc: options[:skip_itc]
    )

    desc "Generate provisioning profile if no present"
    match(
      app_identifier: bundle_identifier,
      type: options[:match_type],
      readonly: false
    )

  end

  desc "Publish to testflight"
  private_lane :publish_testflight do |options|

    pilot

  end

end
